services:
  learnova-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: learnova-backend
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
      - /var/www/html/public/build
    networks:
      - learnova-network

networks:
  learnova-network:
    driver: bridge
